import Head from 'next/head'
import Image from 'next/image'
import cls from '@/styles/Home.module.css'
import { Formik } from "formik"
import { useState } from 'react'
import { userData } from './api/fakeData'
import { useRouter } from 'next/router'
import Deals from '@/components/deals/deals'
import { deal } from './api/fakeData'

export default function Home() {
  // const [user, setUser] = useState(users)
   const router = useRouter()
  const submit = (values) => {
    console.log(values);
    const x = userData.filter((item) => {
      if(item.userName === values.userName && item.password === values.password){
        return item
      } 
    })
    if(x.length > 0){
      router.push("/home")
    }
  }

  const [userss, setUserss] = useState({
    name:"",
    desc:""
  })
  
  const [login, setLogin] = useState({
    userName:"",
    password:""
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cls.main}>
        <h1 className={cls.login}>Login</h1>
          <Formik 
          initialValues={login}
          onSubmit={submit}
          >
      {
        ({
          values,
          handleChange,
          handleSubmit,
          values2

        }) =>(
        
        <form className={cls.form} onSubmit={handleSubmit}>
          <input className={cls.input} name='userName' type="text" value={values.userName} onChange={handleChange} placeholder='Login'/>
          <input className={cls.input} name='password' type="password" value={values.password} onChange={handleChange} placeholder='Password'/>
          <button className={cls.button} type='submit'>
            Login
          </button>
        </form>
      )}
          </Formik>
      </main>
    </>
  )
}
