import Head from 'next/head'
import cls from '@/styles/Home.module.css'
import { Formik } from "formik"
import { useState } from 'react'
import { userData } from './api/fakeData'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const submit = (values) => {
    const x = userData.filter((item) => {
      if(item.userName === values.userName && item.password === values.password){
        return item
      } 
    })
    if(x.length > 0 && x.values.id === userData.id){
      router.push("/home")
    }
    console.log(x);
  }

  const [userss, setUserss] = useState({
    name:"",
    desc:""
  })
  
  const [login, setLogin] = useState({
    userName:"",
    password:""
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/> */}
      </Head>
      <main className={cls.main}>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>
    <span className={cls.span}></span>

      <div className={cls.signin}>
      <div className={cls.content}>
        <h1>sign in</h1>
        <div className={cls.form}>
          <Formik 
          initialValues={login}
          onSubmit={submit}
          >
      {
        ({
          values,
          handleChange,
          handleSubmit,
        }) =>(
        <form className={cls.form} onSubmit={handleSubmit}>
          <div className={cls.inputBx}>
            <input className={cls.input} name='userName' type="text" value={values.userName} onChange={handleChange} placeholder='Login'/>
          </div>
          <div className={cls.inputBx}>
            <input className={cls.input} name='password' type="password" value={values.password} onChange={handleChange} placeholder='Password'/>
          </div>
          <div className={cls.inputBx}>
            <button className={cls.button} type='submit'>
              Login
            </button>
          </div>
        </form>
      )}
          </Formik>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
